### ISSUE TITLE
difficulty for querying

### ISSUE THREAD

**Issue by ibaaj** [nriesterer/pymreasoner#3]
Hello,

I tried the master and development branch but I had difficulties using your software. 
Example : I run cli.py with python3. I want to query simply AA1. 
When i try: 
``` 
query AA1 
```
and debug the query, I got:
```
(setf resp (what-follows? (list (parse '(All A are B)) (parse '(All B are C)))))
HALT
WARNING:mreasoner.mreasoner:QUERY-RES-INVALID:HALT
```
what's wrong? 

Thank you in advance for your help
regards,
PS : The link which download the source is broken (but it isn't a matter, you give us the sources of mReasoner you used).

Edit : the error was on line 60
```
 mreas_path = path + os.sep + 'src'
```
i didn't look at the code but the mreas_path got two dirs src in.
e.g. mreasoner-r6884/src/src/

It's solved.

**Comment by nriesterer** [comment]
Glad that its resolved!
